name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PATH: "$HOME/.local/bin:${{ env.PATH }}"   # تضمین دسترسی به باینری‌های pip --user

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
      with:
        python-version: '3.11'

    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential ccache pkg-config git zip unzip curl rsync \
          openjdk-17-jdk \
          libffi-dev libssl-dev libsqlite3-dev zlib1g-dev liblzma-dev \
          libgl1-mesa-dev libgles2-mesa-dev \
          python3-dev python3-setuptools python3-wheel

    - name: Upgrade pip and install Python deps
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install Cython==0.29.36 buildozer==1.5.0 sh==2.0.6 virtualenv==20.26.6
        python -m buildozer --version || true
        which buildozer || true

    # مرحله‌ی bootstrap برای دانلود SDK/NDK (ممکن است fail شود)
    - name: Bootstrap SDK/NDK download (may fail)
      env:
        BUILDOZER_WARN_ON_ROOT: "0"
      continue-on-error: true
      run: |
        python -m buildozer -v android debug

    # نصب cmdline-tools جدید و پذیرش لایسنس‌ها + ابزارهای پایدار
    - name: Install cmdline-tools and accept licenses
      run: |
        SDK="$HOME/.buildozer/android/platform/android-sdk"
        mkdir -p "$SDK/cmdline-tools"
        curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o /tmp/clt.zip
        rm -rf "$SDK/cmdline-tools/latest"
        mkdir -p "$SDK/cmdline-tools/latest"
        unzip -q /tmp/clt.zip -d "$SDK/cmdline-tools/latest"
        yes | "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" --licenses
        "$SDK/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK" \
          "platform-tools" "build-tools;33.0.2" "platforms;android-33"

    - name: Build APK
      env:
        BUILDOZER_WARN_ON_ROOT: "0"
      run: |
        python -m buildozer -v android debug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: hashashin-apk
        path: bin/*.apk

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: buildozer-logs
        path: |
          .buildozer/**/*.log
          .buildozer/android/platform/android-sdk/**/*
          .buildozer/android/platform/android-ndk-*/**/*
