name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential ccache pkg-config git zip unzip curl rsync \
          openjdk-11-jdk \
          libffi-dev libssl-dev libsqlite3-dev zlib1g-dev liblzma-dev \
          libgl1-mesa-dev libgles2-mesa-dev \
          python3-dev python3-setuptools python3-wheel

    - name: Upgrade pip and install Python deps
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade Cython==0.29.36 buildozer==1.5.0 sh==2.0.6 virtualenv==20.26.6

    # بار اول: اجازه بده SDK/NDK دانلود شود (ممکن است fail شود)
    - name: Bootstrap SDK/NDK download (may fail)
      continue-on-error: true
      env:
        BUILDOZER_WARN_ON_ROOT: "0"
      run: |
        buildozer -v android debug

    # پذیرش غیرتعاملی لایسنس‌ها و نصب ابزارهای پایدار SDK داخل SDKی که buildozer دانلود کرده
    - name: Accept Android SDK licenses and install stable build-tools
      run: |
        SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
        yes | "$SDK_ROOT/tools/bin/sdkmanager" --sdk_root="$SDK_ROOT" --licenses
        "$SDK_ROOT/tools/bin/sdkmanager" --sdk_root="$SDK_ROOT" "platform-tools" "build-tools;33.0.2" "platforms;android-33"

    # بیلد نهایی
    - name: Build APK
      env:
        BUILDOZER_WARN_ON_ROOT: "0"
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: hashashin-apk
        path: bin/*.apk
