name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Pull buildozer image
      run: docker pull kivy/buildozer:latest

    - name: Build APK in Docker (bootstrap + accept licenses + build)
      env:
        BUILDOZER_WARN_ON_ROOT: "0"
      run: |
        docker run --rm \
          -v "${GITHUB_WORKSPACE}:/home/user/app" \
          -w /home/user/app \
          kivy/buildozer:latest bash -lc '
            set -euxo pipefail
            # 1) Bootstrap to download SDK/NDK (may fail)
            buildozer -v android debug || true

            # 2) Find sdkmanager dynamically and accept licenses + install stable tools
            SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
            SDKMGR="$(find "$SDK_ROOT" -type f -name sdkmanager | head -n1 || true)"
            if [ -z "$SDKMGR" ]; then
              # fallback: sometimes tools under cmdline-tools/bin only
              SDKMGR="$(find "$SDK_ROOT/cmdline-tools" -type f -name sdkmanager | head -n1 || true)"
            fi
            if [ -n "$SDKMGR" ]; then
              yes | "$SDKMGR" --sdk_root="$SDK_ROOT" --licenses || true
              "$SDKMGR" --sdk_root="$SDK_ROOT" "platform-tools" "build-tools;33.0.2" "platforms;android-33"
            fi

            # 3) Final build
            buildozer -v android debug
          '

    - name: Upload APK
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392
      with:
        name: hashashin-apk
        path: bin/*.apk
